# Generated by Django 3.2.4 on 2021-06-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0003_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='emailid',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='taskname',
            new_name='message',
        ),
    ]
