# Generated by Django 3.2.4 on 2021-06-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0002_rename_loger_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=120)),
                ('fullname', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120)),
                ('taskname', models.CharField(max_length=120)),
            ],
        ),
    ]
